= XYZ Reader - Solution

From `Udacity Android Developer Nanodegree`

== Project requirements:

- Perform improvements based on users' UI feedback.
- App should use the Design Support library and its provided widget types.
- App should use `CoordinatorLayout` for the main Activity.
- App theme should extend from `AppCompat`.
- App an `AppBar` and associated `ToolBar`s.
- App should provide a Floating Action Button for the most common action(s).
- App should properly specify elevations.
- App should have a consistent color theme defined in `styles.xml`.
- App should provide sufficient space between text and surrounding elements.
- App uses images that are high quality, specific, and full bleed.
- App uses fonts that are either the Android defaults, are complementary, and aren't otherwise distracting.
- App utilizes stable release versions of all libraries, Gradle, and Android Studio.

=== User Feedback for XYZ Reader:

*Lyla says:*

 “This app is starting to shape up but it feels a bit off in quite a few places. I can't put finger on it but it feels odd.”

*Jay says:*

 “Is the text supposed to be so wonky and unreadable? It is not accessible to those of us without perfect vision.&quot;

*Kagure says:*

 “The color scheme is really sad and I shouldn't feel sad.”